name: dart_funcoes_colecoes
description: Modulo da Academia do Flutter de funcoes e colecoes.
version: 1.0.0
homepage: http://academiadoflutter.com.br

environment:
  sdk: '>=2.15.1 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
